name: Public Wiki

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+(-rc.+)?
  pull_request:
    paths:
      - "sdk/docs/**/*"
      - "sdk/examples/**/*"
      - "sdk/bindings/**/*"

jobs:
  public-wiki:
    runs-on: dell
    container:
      image: ${{ vars.DEVCONTAINER_IMAGE }}:${{ vars.DEVCONTAINER_TAG }}
      credentials:
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_PASSWORD }}

    env:
      GIT_DEPTH: 1000
      STORAGE_ACC_DEV: etodevinfrasa
      STORAGE_ACC_MAIN: etodevinfrasa
      RG_DEV: eto-dev-infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}

      - name: Set STORAGE_ACC environment variable
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "STORAGE_ACC=${{ env.STORAGE_ACC_MAIN }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" =~ release/.* ]]; then
            echo "STORAGE_ACC=${{ env.STORAGE_ACC_MAIN }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "pull_request" && \
                  "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "STORAGE_ACC=${{ env.STORAGE_ACC_DEV }}" >> $GITHUB_ENV
          else
            echo "Skipping job as it does not match conditions."
            exit 0
          fi

      - name: Setup Python environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install mkdocs-material mike mkdocs-git-revision-date-localized-plugin \
                      mkdocs-git-committers-plugin-2 mkdocs-git-authors-plugin mkdocs-typedoc azure-cli

      - name: Install project dependencies with pnpm
        run: pnpm install
        working-directory: sdk

      - name: Build wasm-bindings
        run: wasm-pack build --dev --scope eto
        working-directory: sdk/bindings/wasm

      - name: Build the documentation
        run: mkdocs build
        working-directory: sdk

      - name: Azure login
        run: az login -u ${{ secrets.AZURE_USER }} -p ${{ secrets.AZURE_PASS }}

      - name: Set Azure subscription
        run: az account set --subscription "B-SE-1_dev"

      - name: Upload docs to Azure Storage
        run: |
          az storage blob upload-batch --overwrite -s site/ -d '$web' --account-name $STORAGE_ACC
          echo "The book is now available at $(az storage account show -g $AZURE_RG_DEV -n $STORAGE_ACC --query 'primaryEndpoints.web' --output tsv) !"
        working-directory: sdk
